version: "3"
volumes:
  data:
  export:
services:
  laite-psql:
    image: docker.io/postgres:14-alpine
    container_name: laite-psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
